StudentDashboard/HomePage/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.index,name="HomePage"),
]

StudentDashboard/MainDashboard/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'dashboard' 

urlpatterns = [
    path('',views.index,name="MainDashboard"),
    path('add_details',views.add_details,name="add_details"),
    path('search',csrf_exempt(views.ajax_search),name="ajax_search"),
]

StudentDashboard/StudentDashboard/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('',include('HomePage.urls')),
    path('dashboard/',include('MainDashboard.urls'),name="dashboard"),
    path('companies/',include('companies.urls')),
    path('authentication/',include('authentication.urls')),
    path('admin/', admin.site.urls),
    path('preferences/',include('UserPreferences.urls')),
]

StudentDashboard/MainDashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from UserPreferences.models import UserPreference


class Curriculum(models.Model):
    
    user_preference = models.ForeignKey(UserPreference, on_delete=models.CASCADE)
    subject_one=models.CharField(max_length=255)
    subject_two=models.CharField(max_length=255)
    subject_three=models.CharField(max_length=255)
    subject_four=models.CharField(max_length=255)
    subject_five=models.CharField(max_length=255)
    subject_six=models.CharField(max_length=255)
   
    class Meta:
        verbose_name_plural="Curriculums"
        unique_together = (
                'user_preference',
                'subject_one',
                'subject_two',
                'subject_three',
                'subject_four',
                'subject_five',
                'subject_six'
            )
           
    def __str__(self) -> str:
        return f'{self.user_branch_sem}'
    
class UserMarks(models.Model):
   
    user_branch_sem = models.ForeignKey(UserPreference, on_delete=models.CASCADE)
    subject_name = models.CharField(max_length=255)
    quiz1 = models.IntegerField()
    quiz2 = models.IntegerField()
    mid_semester = models.IntegerField()
    end_semester = models.IntegerField()
    
    class Meta:
        verbose_name_plural="UserMarks"
        unique_together = (
                'user_branch_sem',
                'subject_name'
            )
        
    def __str__(self) -> str:
        return f'{self.user_branch_sem}'
    
  

class UpcomingCompanyDetails(models.Model):
    class Meta:
        verbose_name_plural="UpcomingCompanyDetails"
  
    name_of_company=models.CharField(max_length=255)
    year_of_passing=models.IntegerField()
    preferred_branch=models.CharField(max_length=255)
    type=models.CharField(max_length=255)
    mode=models.CharField(max_length=255)
    category=models.CharField(max_length=255)
    
    def __str__(self) -> str:
        return self.name_of_company
  

    

StudentDashboard/MainDashboard/views.py
from django.shortcuts import render,redirect
from .models import UpcomingCompanyDetails,Curriculum
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
import json
from django.db.models import Q
from django.http import JsonResponse
from UserPreferences.models import UserPreference

@login_required(login_url='/authentication/login')

def ajax_search(request):
    
    if request.method=="POST":
        search_str = json.loads(request.body).get('searchText')
        
        company_details = UpcomingCompanyDetails.objects.filter(  
            Q(name_of_company__icontains=search_str) |
            Q(year_of_passing__icontains=search_str) |
            Q(preferred_branch__icontains=search_str) |
            Q(type__icontains=search_str) |
            Q(mode__icontains=search_str) |
            Q(category__icontains=search_str)
        )
            

        data = company_details.values()
        return JsonResponse(list(data), safe=False)



def index(request):
    company_details=UpcomingCompanyDetails.objects.all()
    paginator = Paginator(company_details, 5)
    page_number = request.GET.get('page')
    page_obj = Paginator.get_page(paginator, page_number)
    context={
        "company_details":company_details,
        'page_obj':page_obj,
    }
    return render(request,'MainDashboard/index.html',context)


def add_details(request):
    
    user_preference=None
    if UserPreference.objects.filter(user=request.user).exists()==True:
        user_preference=UserPreference.objects.get(user=request.user)
    
    subjects=[]
    if(user_preference):
        mixedbranch = user_preference.branch

        branch = mixedbranch.split('-')[1].strip()
        
        
        semester = user_preference.semester
        
        get_subjects=Curriculum.objects.filter(branch=branch,semester=semester).first()
        
        if get_subjects:
            subjects=[get_subjects.subject_one,
            get_subjects.subject_two,
            get_subjects.subject_three,
            get_subjects.subject_four,
            get_subjects.subject_five,
            get_subjects.subject_six]
            
       
    
    if request.method=="GET":
        return render(request,'MainDashboard/add_details.html',{"subjects":subjects})
    
    
            
    

StudentDashboard/templates/MainDashboard/add_details.html
{% extends "base.html" %} 
{% block content %}

{% load static %}


<div class="container mt-3">
    
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url "dashboard:MainDashboard" %}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add Details</li>
        </ol>
    </nav>

    
    <div class="card">
        <div class="card-body">
            <div class="button-container">
                <button class="btn btn-primary">First Semester</button>
                <button class="btn btn-primary">Second Semester</button>
                <button class="btn btn-primary">Third Semester</button>
                <button class="btn btn-primary">Fourth Semester</button>
                <button class="btn btn-primary">Fifth Semester</button>
                <button class="btn btn-primary">Six Semester</button>
                <button class="btn btn-primary">Seventh Semester</button>
            </div>
        </div>
    </div>

    <div>
        <table class="table table-stripped table-hover">
            <thead>
                <tr>
                    <th>Subject</th>
                    <th>Quiz 1</th>
                    <th>Quiz 2</th>
                    <th>Mid Semester</th>
                    <th>End Semester</th>
                </tr> 
            </thead>
    
            <tbody>
                <form action="{% url "add_details" %}" method="POST">
                    {% csrf_token %}
                    {% for subject in subjects %}
                    <tr>
                        <td><input type="number" name="" class="form-control" placeholder="Quiz 1"></td>
                        <td><input type="number" name="" class="form-control" placeholder="Quiz 2"></td>
                        <td><input type="number" name="" class="form-control" placeholder="Mid Semester"></td>
                        <td><input type="number" name="" class="form-control" placeholder="End Semester"></td>
                        <td><input class="btn btn-outline-secondary" type="submit" value="Save"/></td>
                    </tr> 
                
                    {% endfor %}
                </form>
                
            </tbody>
            
        </table>
    </div>


    
   

</div>

{% endblock content %}

StudentDashboard/templates/MainDashboard/index.html
{% extends "base.html" %} 
{% load static %}
{% block content %}

<div class="container mt-3">
    {% include "partials/messages.html" %}
    

    <div class="row">
        <div class="col-md-10">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active">Dashboard</li>
                </ol>
            </nav>
        </div>

        <div class="col-md-2">
            <a href="{% url "dashboard:add_details" %}" class="btn btn-primary">Add Details</a>
        </div>

    </div>

</div>

<div class="row">
    <div class="col-md-8"></div>
    <div class="col-md-3">
      <div class="form-group">
        <input type="text" class="form-control" id="searchField" placeholder="Search">
      </div>
    </div>
</div>

<div class="container mt-2">

    {% if company_details.count %}
    
    <div class="app_table">
        <table class="table table-stripped table-hover">
            <thead>
                <tr>
                    <th>Name of Company</th>
                    <th>Batch</th>
                    <th>Preferred Branch</th>
                    <th>Type</th>
                    <th>Mode</th>
                    <th>Category</th>
                </tr> 
            </thead>
    
            <tbody>
                {% for company in page_obj %}
                <tr>
                    <td>{{company.name_of_company}}</td>
                    <td>{{company.year_of_passing}}</td>
                    <td>{{company.preferred_branch}}</td>
                    <td>{{company.type}}</td>
                    <td>{{company.mode}}</td>
                    <td>{{company.category}}</td>
                </tr>
                {% endfor %}
            </tbody>
            
        </table>
    </div>
    <p class="no_results" style="display: none;">No Results Found </p>
    <div class="table_output">
        <table class="table table-stripped table-hover">
            <thead>
                <tr>
                    <th>Name of Company</th>
                    <th>Batch</th>
                    <th>Preferred Branch</th>
                    <th>Type</th>
                    <th>Mode</th>
                    <th>Category</th>
                </tr> 
            </thead>
    
            <tbody class="table_body">
                
            </tbody>
            
        </table>
    </div>
    

    <div class="pagination_container">
        <div class="">
          Showing page {{page_obj.number}} of {{ page_obj.paginator.num_pages }}
        </div>
        
        <ul class="pagination align-right float-right mr-auto">
          {% if page_obj.has_previous %}
          <li {% if page_obj.number == 1 %} class="page-item active" {% endif %}><a class="page-link" href="?page=1">&laquo; 1</a></li>
          <li class="page-item"> <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
          {% endif %}
    
          {% if page_obj.has_next %}
          <li class="page-item"> <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
          <li class="page-item"> <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages}} &raquo;</a></li>
          {% endif %}
        </ul>
    </div>

    {% endif %}
    

</div>


<script src="{% static 'js/ajax_search.js' %}"></script>


{% endblock content %}